Workaround for problem with loading liblzma.so (issue #29)

diff --git a/linux/products/lightzone b/linux/products/lightzone
--- a/linux/products/lightzone
+++ b/linux/products/lightzone
@@ -12,4 +12,11 @@ else
         maxmem=512000
 fi
 
-(cd "/opt/lightzone" && LD_LIBRARY_PATH="/opt/lightzone" exec java -Xmx${maxmem}k -Djava.library.path="/opt/lightzone" -Dfile.encoding=UTF8 -classpath "/opt/lightzone/*" com.lightcrafts.platform.linux.LinuxLauncher ${@} )
+# workaround for loading problem with liblzma.so
+lzmalibrary=`find /usr/lib -name "liblzma.so*" | head -1`
+if [ -z "$lzmalibrary" ]; then
+   echo "liblzma was not found on the system; exiting"
+   exit 1
+fi;
+
+(cd "/opt/lightzone" && LD_PRELOAD="$lzmalibrary" LD_LIBRARY_PATH="/opt/lightzone" exec java -Xmx${maxmem}k -Djava.library.path="/opt/lightzone" -Dfile.encoding=UTF8 -classpath "/opt/lightzone/*" com.lightcrafts.platform.linux.LinuxLauncher ${@} )
